#! /bin/sh
source  colors

# Rosé pine 
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		let name++
	done
}
workspaces

bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#bd93f9"
bspc config normal_border_color "#282a36"
bspc config active_border_color "#bbbbbb"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspace 1 (Terminals)
#declare -a terminal=(kitty)
#for i in ${terminal[@]}; do
#    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
#declare -a web=(qutebrowser discord-canary)
#for i in ${web[@]}; do
#    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
#declare -a filem=(Thunar)
#for i in ${filem[@]}; do
#    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
#declare -a office=(Code)
#for i in ${office[@]}; do
#    bspc rule -a $i desktop='^4' follow=on focus=on; done
    
# workspace 5 (Media)
#declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
#"VirtualBox Manager")
#for i in ${media[@]}; do
#    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 6 (Music)
#declare -a music=(Spotify)
#for i in ${music[@]}; do
#    bspc rule -a $i desktop='^4' follow=on focus=on; done


# workspace 7 (Settings)
#declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
#Pavucontrol Xfce4-settings-manager)
#for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a 'kade engine.exe' state=floating
bspc rule -a 'Kade Engine' state=floating

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey

# Launch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Source Code Pro Medium 10" \
-lb "${bg}FF" -lf "${fg}FF" -lfr "${altbg}FF" \
-nb "${bg}FF" -nf "${fg}FF" -nfr "${altbg}FF" \
-cb "${bg}FF" -cf "#BF616AFF" -cfr "#BF616AFF" &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
polydock &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &
xrandr --output HDMI-0 --mode 1920x1080 --rate 144
